name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install AWS CLI
      run: python -m pip install awscli
    - name: Configure AWS CLI for R2
      run: |
        aws --profile r2-deploy configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
        aws --profile r2-deploy configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
    - name: Deploy site to R2 bucket
      run: |
        aws s3api sync --endpoint-url ${{ secrets.R2_ENDPOINT_URL }} ${SOURCE_DIR} s3://${R2_BUCKET} \
          --profile r2-deploy --no-progress --follow-symlinks --delete
      env:
        SOURCE_DIR: dist
        R2_BUCKET: marx-sh