name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install AWS CLI
      run: python -m pip install awscli
    - name: Configure AWS CLI for R2
      run: |
        aws configure --profile r2-deploy <<-EOF > /dev/null 2>&1
        ${{ secrets.R2_ACCESS_KEY_ID }}
        ${{ secrets.R2_SECRET_ACCESS_KEY }}
        text
        EOF
    - name: Deploy site to R2 bucket
      run: |
        aws s3 sync ${SOURCE_DIR} ${{ secrets.R2_BUCKET }} --profile r2-deploy --no-progress \
          --follow-symlinks --delete
      env:
        SOURCE_DIR: dist